export const skeletonData = [
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    }, {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },
    {
        id: "------",
        country: "",
        device: "------",
        browser: "------",
        trafficSource: "------",
        firstSession: 0,
        convertedSession: 0,
        trails: [{
            id: 0,
            url: "------",
            time: 0,
            sessionDate: 0,
        }],
    },



];